---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    If Miriam doesn't earn an A, then nobody should, because she consistently put in effort week after week, completing practice activities and revisions with a positive attitude, while expanding her learning, working a job, and managing other challenging classes.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

The most difficult part of the class for me was Lab 5, its open-ended nature made it challenging to know where to start, and I struggled with understanding and applying join functions effectively.

1.  What was the easiest part of the class for you? Explain why.

    The easiest part of the class for me was listening to lectures and taking notes, as Dr. T's clear explanations and examples made the material easy to follow.

2.  What part of the class surprised or interested you the most? Explain why.

    The most interesting part of the class was the Practice Activities, as I enjoyed combining lectures with hands-on practice and was especially motivated by the puzzle-like assignments.

3.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

My advice would be to thoroughly complete the pre-class practice activities. They are there to help, and doing this work significantly improves your understanding and ability to implement what you learn.
